// packages/vue/src/components/Handle.vue
<script lang="ts" setup>
import { Matrix, Mat, Angle } from "@free-transform/core";
import { computed, inject, Ref } from "vue";

export interface Props {
  position: [number, number];
  origin?: [number, number];
  type: "warp" | "rotate" | "scale";
  offset?: [number, number];
}

type Handler = (handle: [number, number], event: PointerEvent) => void;

const props = withDefaults(defineProps<Props>(), {
  offset: () => [0, 0],
});

const width = inject<Ref<number>>("width");

const height = inject<Ref<number>>("height");

const affineMatrix = inject<Ref<Matrix>>("affineMatrix");
const matrix = inject<Ref<Matrix>>("matrix");

const handlers = {
  scale: inject<Handler>("scale"),
  rotate: inject<Handler>("rotate"),
  warp: inject<Handler>("warp"),
};

const transform = computed(() => {
  if (!affineMatrix || !matrix || !width || !height) {
    return "";
  }

  const decomposed = Mat.decompose(affineMatrix.value);

  const point1 = Mat.toPoint(matrix.value, [
    Math.floor(props.position[0]) * width.value,
    Math.floor(props.position[1]) * height.value,
  ]);

  const point2 = Mat.toPoint(matrix.value, [
    Math.ceil(props.position[0]) * width.value,
    Math.ceil(props.position[1]) * height.value,
  ]);

  const find = (p1: number, p2: number, per: number) => p1 + (p2 - p1) * per;

  const percentage = Math.abs(props.position[0] - props.position[1]);

  const point = [
    find(point1[0], point2[0], percentage),
    find(point1[1], point2[1], percentage),
  ];

  const radians = decomposed.rotation.angle;

  const [x, y] = Angle.point([props.offset[0], props.offset[1]], radians);

  return `translate(${point[0] + x}px, ${
    point[1] + y
  }px) rotate(${Angle.degrees(-radians)}deg)`;
});

const onDown = (event: PointerEvent) => {
  handlers[props.type]?.(props.origin || props.position, event);
};
</script>

<template>
  <div
    :style="{
      transform,
    }"
    @pointerdown.stop="onDown"
  ></div>
</template>

// packages/react/src/components/handle.tsx
import {
  ComponentProps,
  forwardRef,
  useCallback,
  useMemo,
  PointerEvent as ReactPointerEvent,
  useRef,
  useLayoutEffect,
  useState,
} from "react";
import { useFreeTransform } from "./free-transform";
import {
  Angle,
  Mat,
  Matrix,
  Point,
  makePerspectiveMatrix,
  makeWarpPoints,
  rotate,
  scale,
  warp,
} from "@free-transform/core";
import { assignRefs } from "../utils/assign-refs"; 

type Props = {
  origin: Point;
  position?: Point;
  type: "rotate" | "scale" | "warp";
  offset?: Point;
};
export const Handle = forwardRef<HTMLDivElement, ComponentProps<"div"> & Props>(
  function Handle(
    {
      origin,
      type,
      position = origin,
      offset: handleOffset = [0, 0],
      ...props
    },
    ref
  ) {
    const rref = useRef<HTMLDivElement>(null);

    useLayoutEffect(() => {
      if (!rref.current) {
        return;
      }
      const box = rref.current.getBoundingClientRect();
      setCenterMargin([box.width / 2, box.height / 2]);
    }, []);

    const {
      matrix,
      width,
      height,
      x,
      y,
      onUpdate,
      offset = [0, 0],
      warp: warpPonts,
      perspectiveMatrix,
      finalMatrix,
    } = useFreeTransform();

    const [centerMargin, setCenterMargin] = useState<Point>([0, 0]);

    const transform = useMemo(() => {
      const decomposed = Mat.decompose(matrix);
      let radians = decomposed.rotation;

      const point = Mat.toPoint(finalMatrix, [
        position[0] * width,
        position[1] * height,
      ]);

      const offsetPosition = Angle.point(
        [
          (handleOffset[0] - centerMargin[0]) * Math.sign(decomposed.scale[0]),
          (handleOffset[1] - centerMargin[1]) * Math.sign(decomposed.scale[1]),
        ],
        radians
      );

      const final = [
        point[0] + x + offsetPosition[0],
        point[1] + y + offsetPosition[1],
      ];

      const scaleSign = [
        Math.sign(decomposed.scale[0]),
        Math.sign(decomposed.scale[1]),
      ];

      return {
        style: `
        translate(${final[0]}px, ${final[1]}px)        
        rotate(${-radians}rad)
        scale(${scaleSign[0]}, ${scaleSign[1]})
        `,
        radians,
      };
    }, [matrix, finalMatrix, width, height, x, y, origin, type, centerMargin]);

    const handler = useCallback(
      (startEvent: ReactPointerEvent) => {
        switch (type) {
          case "scale":
            return scale(
              origin,
              {
                start: [startEvent.clientX, startEvent.clientY],
                width,
                height,
                matrix: finalMatrix,
                affineMatrix: matrix,
                perspectiveMatrix,
                // scaleLimit: [0.1, Infinity],
                fromCenter: (event: any) => event.altKey,
                aspectRatio: (event: any) => event.shiftKey,
              },
              onUpdate
            );
          case "rotate":
            return rotate(
              origin,
              {
                start: [startEvent.clientX, startEvent.clientY],
                width,
                height,
                matrix: finalMatrix,
                affineMatrix: matrix,
                x,
                y,
                offset,
              },
              onUpdate
            );
          case "warp":
            return warp(
              origin,
              {
                start: [startEvent.clientX, startEvent.clientY],
                matrix,

                warp: warpPonts || makeWarpPoints(width, height),
              },
              onUpdate
            );
        }
      },
      [width, height, matrix, origin, type]
    );

    return (
      <div
        ref={assignRefs(ref, rref)}
        {...props}
        onPointerDown={(startEvent) => {
          startEvent.preventDefault();
          startEvent.stopPropagation();

          const onDrag = handler(startEvent);

          const onMouseUp = (event: PointerEvent) => {
            document.removeEventListener("pointermove", onDrag);
            document.removeEventListener("pointerup", onMouseUp);
          };

          document.addEventListener("pointermove", onDrag);
          document.addEventListener("pointerup", onMouseUp);
        }}
        style={{
          transform: transform.style,
          position: "absolute",
          transformOrigin: "0 0",
          ...(props.style || {}),
        }}
      />
    );
  }
);
